postgresqlPassword: postgresql
postgresqlPostgresPassword: postgresql
postgresqlDatabase: peertube
persistence:
  enabled: true
  size: 1Gi
volumePermissions:
  enabled: true
primary:
  annotations:
    k10.kasten.io/forcegenericbackup: 'true'