apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  namespace: argocd
  name: argocd-jeancloudeclub-applicationset
spec:
  generators:
  - git:
      repoURL: https://github.com/constructions-incongrues/club.jeancloude.k8s.git
      revision: HEAD
      directories:
      - path: src/applications/*
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: jeancloude-club
      source:
        repoURL: https://github.com/constructions-incongrues/club.jeancloude.k8s.git
        targetRevision: HEAD
        path: '{{`{{path}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{path.basename}}`}}'