apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: peertube

bases:
- https://github.com/coopgo/peertube-k8s/

resources:
- ingress.yaml
- secret.yaml

patchesJson6902:
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: peertube