apiVersion: v1
kind: Secret
metadata:
  name: peertube-secret
  namespace: peertube
type: bootstrap.kubernetes.io/generic
stringData:
  POSTGRES_USER: "postgresql"
  POSTGRES_PASSWORD: "postgresql"
  POSTGRES_DB: "peertube"
  PEERTUBE_DB_USERNAME: "peertube"
  PEERTUBE_DB_PASSWORD: "peertube"
  PEERTUBE_DB_SSL: "true"
  PEERTUBE_DB_HOSTNAME: "postgresql"
  PEERTUBE_DB_PORT: "12345"
  PEERTUBE_WEBSERVER_HOSTNAME: "peertube.your-server.com"
  PEERTUBE_SMTP_USERNAME: "example@your-server.com"
  PEERTUBE_SMTP_PASSWORD: "smtppassword"
  PEERTUBE_SMTP_HOSTNAME: "mail.your-server.com"
  PEERTUBE_SMTP_PORT: "587"
  PEERTUBE_SMTP_FROM: "noreply@your-server.com"
  PEERTUBE_SMTP_TLS: "false"
  PEERTUBE_SMTP_DISABLE_STARTTLS: "false"
  PEERTUBE_ADMIN_EMAIL: "you@your-server.com"
  PEERTUBE_OBJECT_STORAGE_ENABLED: "true"
  PEERTUBE_OBJECT_STORAGE_ENDPOINT: "s3.fr-par.scw.cloud"
  PEERTUBE_OBJECT_STORAGE_REGION: "fr-par"
  PEERTUBE_OBJECT_STORAGE_STREAMING_PLAYLISTS_BUCKET_NAME: "yourbucket"
  PEERTUBE_OBJECT_STORAGE_STREAMING_PLAYLISTS_PREFIX: "streaming/"
  PEERTUBE_OBJECT_STORAGE_VIDEOS_BUCKET_NAME: "yourbucket"
  PEERTUBE_OBJECT_STORAGE_VIDEOS_PREFIX: "videos/"
  AWS_ACCESS_KEY_ID: "S3ACCESSKEY"
  AWS_SECRET_ACCESS_KEY: "S3SECRETKEY"
  PEERTUBE_INSTANCE_NAME: "Club Téloche"
  PEERTUBE_INSTANCE_DESCRIPTION: "Le Panégyrique de fin"